### ISSUE TITLE
Metapackage `ros-humble-turtlebot3-manipulation-*.deb` cannot be found on `http://packages.ros.org/ros2/ubuntu`

### ISSUE THREAD

**Issue by goekce** [ROBOTIS-GIT/turtlebot3_manipulation#65] opened 2023-08-09 16:01 UTC
I would like to install the metapackage `ros-humble-turtlebot3-manipulation` using `apt` however the package cannot be found. I can see it on [ROS Index](https://index.ros.org/p/turtlebot3_manipulation/github-ROBOTIS-GIT-turtlebot3_manipulation/) and also on [Ubuntu ROS package mirror](http://packages.ros.org/ros2/ubuntu). Somehow [there is no `deb` for this metapackage but only source](http://packages.ros.org/ros2/ubuntu/pool/main/r/ros-humble-turtlebot3-manipulation/). Is this a bug or feature?

**Comment by sunghowoo** [comment] 2024-09-17 03:36
It appears that the ros-humble-turtlebot3-manipulation metapackage is only available as source at this time. This is likely not a bug but a feature, where the package is yet to have precompiled binaries (deb) in the apt repository. I believe the question has been answered, so I will close this issue

**Closed as completed by sunghowoo** 2024-09-17 03:36 UTC
